package model.enums;

public enum PriceListItemType {
    MONTHLY_SUBSCRIPTION, YEARLY_SUBSCRIPTION, PRIORITY_PICKUP,
    PRIORITY_RETURN, EXTENDED_RETENTION, PENALTY,
    CHILD_DISCOUNT, STUDENT_DISCOUNT, PUPIL_DISCOUNT, RETIREE_DISCOUNT,
}
